apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-lab-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: gitops-lab
  source:
    repoURL: https://github.com/firdousali86/GCPTestProject.git
    targetRevision: main
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops-lab-dev
  syncPolicy:
    automated:          # dev: every commit deploys itself
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
